export default [
  "userId",
  "reactions",
  "dimensions",
  "images",
  "meta",
  "reviews",
  "tags",
  "discountPercentage",
  "rating",
  "warrantyInformation",
  "availabilityStatus	",
  "returnPolicy",
  "minimumOrderQuantity",
  "thumbnail",
  "shippingInformation",
  "description",
  "availabilityStatus",
  "weight",
  "sku",
  "brand",
];
